spring:
  application:
    name: RabbitmqDemo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    virtual-host: /rabbitmq-demo
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000
        multiplier: 2
    listener:
      simple:
        prefetch: 1               # 每次只读一条信息
        acknowledge-mode: manual  # 手动确认,确保消息至少被消费一次

server:
  port: 8081



